seed_everything: 35
log_level: debug

data:
  class_path: eigenn.dataset.matbench.MatbenchDataMoldule
  init_args:
    root: ../eigenn/dataset/matbench
    trainset_filename: matbench_dielectric_n20.json
    valset_filename: matbench_dielectric_n20.json
    testset_filename: matbench_dielectric_n20.json
    r_cut: 5.0
    loader_kwargs:
      batch_size: 10

model:
  backbone_hparams:
    #
    # input embedding
    #

    # atom species embedding
    species_embedding_dim: 32
    # species_embedding_irreps_out: 16x0e # not needed when using SpeciesEmbedding

    # spherical harmonics embedding of edge direction
    irreps_edge_sh: 0e + 1o + 2e

    # radial edge distance embedding
    num_radial_basis: 8
    radial_basis_r_cut: 5.0 # should be the same as r_cut in dataset

    #
    # conv layers
    #
    num_layers: 3

    # radial network
    invariant_layers: 2 # number of radial layers, we found it important to keep this small, 1 or 2
    invariant_neurons: 64 # number of hidden neurons in radial function, smaller is faster
    avg_num_neighbors: null # number of neighbors to divide by, None => no normalization.
    use_sc: true

    conv_layer_irreps: 32x0o + 32x0e + 16x1o + 16x1e + 8x2o + 8x2e
    nonlinearity_type: gate
    resnet: true

    #
    # output
    #
    conv_to_output_hidden_irreps_out: 16x0e
    reduce: sum

  task_hparams:
    task_name: n

trainer:
  max_epochs: 2
  num_nodes: 1
  gpus: null
  detect_anomaly: false # should be true only at debugging
  track_grad_norm: -1 # should be value other than -1 only at debugging
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/score
        mode: min
        save_top_k: 3
        save_last: true
        verbose: False
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val/score
        mode: min
        patience: 100
        min_delta: 0
        verbose: true
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: -1
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      save_dir: wandb_logs # should be provided to make cli save config work
      project: tmp-eigenn

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001

lr_scheduler:
  class_path: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  init_args:
    warmup_epochs: 10
    max_epochs: 20 # this should be set to trainer.max_epochs
    eta_min: 0.0
