seed_everything: 35
restore: false
data:
  class_path: eigenn.dataset.matbench.MatbenchDataMoldule
  init_args:
    root: /Users/mjwen/Documents/Dataset/matbench/matbench_dielectric
    trainset_filename: matbench_dielectric_val.json
    valset_filename: matbench_dielectric_val.json
    testset_filename: matbench_dielectric_val.json
    r_cut: 5.0
    loader_kwargs:
      batch_size: 10

model:
  backbone_hparams:
    num_layers: 3
    r_max: 5.0 # this should be the same as r_cut in dataset
    species_embedding_irreps_out: 16x0e
    feature_irreps_hidden: 32x0o + 32x0e + 16x1o + 16x1e
    irreps_edge_sh: 0e + 1o
  task_hparams:
    task_name: n

trainer:
  max_epochs: 2
  num_nodes: 1
  gpus: null
  terminate_on_nan: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/score
        mode: min
        save_top_k: 3
        save_last: true
        verbose: False
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val/score
        mode: min
        patience: 100
        min_delta: 0
        verbose: true
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      save_dir: wandb_logs # should be provided to make cli save config work
      project: tmp-eigenn

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001

lr_scheduler:
  class_path: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  init_args:
    warmup_epochs: 10
    max_epochs: 20 # this should be set to trainer.max_epochs
    eta_min: 0.0
