exclude: ^docs/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-encoding-pragma
        args:
          - --remove

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --filter-files
        exclude: ^docs/

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: ^docs/

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
