name: eigenn
channels:
  - conda-forge
  - defaults
dependencies:
  - pymatgen=2022.0.14
  - loguru=0.5.3
  - pandas=1.3.3
  - pytest=6.2.5
  - mamba
  - flake8
  - black
  - pip:
      - pytorch-lightning==1.4.6
      - lightning-bolts==0.4.0
      - https://github.com/mir-group/nequip.git
