name: eigenn
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - pyg=2.0.1
  - pytorch=1.9.0
  - pymatgen=2022.0.14
  - loguru=0.5.3
  - pandas=1.3.3
  - pytest=6.2.5
  - flake8
  - black
  - pip:
      - lightning-bolts==0.4.0
      - pytorch-lightning==1.4.6
