name: eigenn
channels:
  - conda-forge
  - defaults
dependencies:
  - pymatgen=2022.0.14
  - loguru=0.5.3
  - pandas=1.3.3
  - pytest=6.2.5
  - pytorch-lightning==1.5.2
  - torchmetrics==0.6.0
  - mamba
  - flake8
  - black
  - pip:
      - lightning-bolts==0.4.0
      - git+https://github.com/mir-group/nequip.git
