name: eigenn
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python==3.9.12
  - pytorch==1.11.0
  - pyg==2.0.4
  - pytorch-lightning==1.6.0
  - torchmetrics==0.7.3
  - lightning-bolts==0.5.0
  - pymatgen==2022.0.14
  - openbabel==3.1.1
  - wandb==0.12.11
  - loguru==0.5.3
  - jsonargparse==4.5.0
  - pip:
      - torchtyping
      - e3nn
