name: eigenn
channels:
  - conda-forge
  - defaults
dependencies:
  - pymatgen=2022.0.14
  - loguru=0.5.3
  - pandas=1.3.3
  - pytest=6.2.5
  - pytorch-lightning==1.5.8
  - torchmetrics==0.6.0
  - jsonargparse==3.19.2
  - openbabel==3.1.1
  - wandb
  - mamba
  - flake8
  - black
  - pip:
      - lightning-bolts==0.4.0
