data:
  compute_dataset_statistics: false
  loader_kwargs:
    batch_size: 32
    num_workers: 0
    shuffle: true
  r_cut: 5.0
  reuse: true
  root: .
  tensor_target_format: irreps
  tensor_target_formula: ijkl=jikl=klij
  tensor_target_name: elastic_tensor_full
  testset_filename: /project/wen/mjwen/playground/matten_playground/elastic_tensor/dataset/20230322/crystal_elasticity_filtered_test.json
  trainset_filename: /project/wen/mjwen/playground/matten_playground/elastic_tensor/dataset/20230322/crystal_elasticity_filtered_train.json
  valset_filename: /project/wen/mjwen/playground/matten_playground/elastic_tensor/dataset/20230322/crystal_elasticity_filtered_val.json
log_level: info
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
  init_args:
    factor: 0.5
    mode: min
    patience: 50
    verbose: true
model:
  average_num_neighbors: auto
  conv_layer_irreps: 32x0o+32x0e + 16x1o+16x1e + 4x2o+4x2e + 2x3o+2x3e + 2x4e
  conv_to_output_hidden_irreps_out: 16x0e + 2x2e + 4e
  invariant_layers: 2
  invariant_neurons: 32
  irreps_edge_sh: 0e + 1o + 2e + 3o + 4e
  nonlinearity_type: gate
  normalization: batch
  num_layers: 3
  num_radial_basis: 8
  output_format: irreps
  output_formula: ijkl=jikl=klij
  radial_basis_end: 5.0
  radial_basis_start: 0.0
  radial_basis_type: bessel
  reduce: mean
  resnet: true
  species_embedding_dim: 16
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.01
    weight_decay: 1.0e-05
restore: true
seed_everything: 3
trainer:
  accelerator: gpu
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      mode: min
      monitor: val/score
      save_last: true
      save_top_k: 3
      verbose: false
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      min_delta: 0
      mode: min
      monitor: val/score
      patience: 150
      verbose: true
  - class_path: pytorch_lightning.callbacks.ModelSummary
    init_args:
      max_depth: -1
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.wandb.WandbLogger
    init_args:
      project: 20230627_tensor_production
      save_dir: matten_logs
  max_epochs: 1000
  num_nodes: 1
